name: Discord Notification

on: [push]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Enviar notificação para o Discord
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        message: |
          **[${{ github.repository }}:master]** 1 new commit
          `${{ github.event.head_commit.id }}` [${{ github.event.head_commit.message.split('\n')[0] }}] - ${{ github.actor }}
